import{APP_VERSION,DAYS}from'./config.js';import{all,put,setSetting,setting}from'./db.js';import{makeTask,defaultSettings,debt,today}from'./model.js';import{dirty,tombstone,syncAll}from'./sync.js';import{signIn,signUp,signOut,currentSession}from'./auth.js';import{enablePush}from'./push.js';import{importLegacy}from'./import.js';
const $=s=>document.querySelector(s);let settingsRec=null,deferredInstall=null;
function toast(m){const e=$('#toast');e.textContent=m;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2600)}
function fmtInterval(n){return +n===1?'cada día':`cada ${n} días`}
async function ensureSettings(){const rows=await all();settingsRec=rows.find(x=>x.type==='settings');if(!settingsRec){settingsRec=defaultSettings();await put(settingsRec)}applyTheme()}
function applyTheme(){const dark=settingsRec?.themeName==='taskium_dark';document.documentElement.dataset.theme=dark?'dark':'light';$('#themeBtn').textContent=dark?'Claro':'Oscuro'}
async function saveSettings(){await dirty(settingsRec);await renderStatus();syncAll().catch(()=>{})}
async function render(){await ensureSettings();const rows=(await all()).filter(x=>x.type==='task'&&!x._sync?.deleted);rows.sort((a,b)=>(a.order??a.createdAt).toString().localeCompare((b.order??b.createdAt).toString()));const ones=rows.filter(x=>x.taskKind==='one_time'),recs=rows.filter(x=>x.taskKind==='recurring');renderList($('#oneList'),ones,'one');renderList($('#recList'),recs,'recurring');$('#oneCount').textContent=ones.length;const debtUnits=recs.reduce((s,t)=>s+debt(t),0);$('#recCount').textContent=`${recs.length} · deuda ${debtUnits}`;renderAlarms();await renderAuth();await renderStatus();if(location.hash.includes('alert')||location.hash.includes('tasks')){const total=ones.length+debtUnits;if(total>0)$('#alertBanner').classList.remove('hidden')}}
function renderList(host,rows,cls){host.innerHTML='';if(!rows.length){host.innerHTML='<div class="empty">Sin tareas.</div>';return}rows.forEach((t,i)=>{const d=debt(t);const el=document.createElement('div');el.className=`task ${cls}`;el.innerHTML=`<div class="task-main"><div class="task-text"></div><div class="meta"></div></div><div class="task-actions"><button data-a="up" title="Subir">↑</button><button data-a="down" title="Bajar">↓</button>${t.taskKind==='one_time'?'<button data-a="done" class="done">Hecha</button>':`<button data-a="progress" class="done" ${d<=0?'disabled':''}>Hecha 1</button>`}<button data-a="delete" class="danger" title="Borrar">×</button></div>`;el.querySelector('.task-text').textContent=t.text;el.querySelector('.meta').innerHTML=t.taskKind==='recurring'?`${fmtInterval(t.intervalDays)} · origen ${t.anchorDate} <span class="debt">${d} pendiente${d===1?'':'s'}</span>`:`Creada ${String(t.createdAt).slice(0,10)}`;el.querySelector('[data-a=up]').disabled=i===0;el.querySelector('[data-a=down]').disabled=i===rows.length-1;el.addEventListener('click',async ev=>{const a=ev.target.dataset.a;if(!a)return;if(a==='done'||a==='delete'){if(!confirm(`“${t.text}” se eliminará permanentemente. ¿Deseas continuar?`))return;await tombstone(t)}else if(a==='progress'){if(d<=0)return;t.completedCount=(+t.completedCount||0)+1;await dirty(t)}else if(a==='up'||a==='down'){const j=a==='up'?i-1:i+1;const other=rows[j];const ao=t.order??i,bo=other.order??j;t.order=bo;other.order=ao;await dirty(t);await dirty(other)}await render();syncAll().then(render).catch(()=>{})});host.appendChild(el)})}
function renderAlarms(){const host=$('#alarmsGrid');host.innerHTML='';settingsRec.alarmsByDay.forEach((d,di)=>{const e=document.createElement('div');e.className='day';e.innerHTML=`<h3>${d.day_name}</h3>`;d.slots.forEach((s,si)=>{const row=document.createElement('label');row.className='slot';row.innerHTML=`<input type="checkbox" ${s.enabled?'checked':''}><input type="time" value="${String(s.hour).padStart(2,'0')}:${String(s.minute).padStart(2,'0')}">`;const cb=row.children[0],tm=row.children[1];const save=async()=>{s.enabled=cb.checked;const[h,m]=tm.value.split(':').map(Number);s.hour=h;s.minute=m;await saveSettings()};cb.onchange=save;tm.onchange=save;e.appendChild(row)});host.appendChild(e)});$('#snoozeMinutes').value=settingsRec.snoozeMinutes}
async function renderAuth(){const s=await currentSession();$('#authLoggedOut').classList.toggle('hidden',!!s);$('#authLoggedIn').classList.toggle('hidden',!s);if(s)$('#userEmail').textContent=s.user?.email||'usuario'}
async function renderStatus(){const s=await currentSession();const last=await setting('lastSyncAt',null);$('#syncStatus').textContent=!navigator.onLine?'Sin conexión':s?(last?'Sincronizado':'Conectado'):'Solo local'}
$('#taskKind').onchange=()=>$('#intervalWrap').classList.toggle('hidden',$('#taskKind').value!=='recurring');$('#addForm').onsubmit=async e=>{e.preventDefault();const text=$('#taskText').value.trim();if(!text)return;const t=makeTask(text,$('#taskKind').value,+$('#intervalDays').value);const same=(await all()).filter(x=>x.type==='task'&&x.taskKind===t.taskKind);t.order=same.length;await put(t);$('#taskText').value='';await render();syncAll().then(render).catch(()=>{})};
$('#themeBtn').onclick=async()=>{settingsRec.themeName=settingsRec.themeName==='taskium_dark'?'taskium_light':'taskium_dark';await saveSettings();applyTheme()};
$('#snoozeMinutes').onchange=async()=>{settingsRec.snoozeMinutes=Math.min(60,Math.max(1,+$('#snoozeMinutes').value||10));await saveSettings()};
$('#authForm').onsubmit=async e=>{e.preventDefault();try{await signIn($('#email').value,$('#password').value);toast('Sesión iniciada');await syncAll();await render()}catch(err){toast(err.message)}};$('#signupBtn').onclick=async()=>{try{const r=await signUp($('#email').value,$('#password').value);toast(r.s?'Cuenta creada y sesión iniciada':'Cuenta creada. Revisa tu correo si Supabase pide confirmación.');await render()}catch(err){toast(err.message)}};$('#signoutBtn').onclick=async()=>{await signOut();await render()};$('#syncBtn').onclick=async()=>{try{await syncAll();toast('Sincronizado');await render()}catch(e){toast(e.message)}};
$('#enableNotificationsBtn').onclick=async()=>{try{await enablePush();toast('Notificaciones activadas')}catch(e){toast(e.message)}};
$('#snoozeNowBtn').onclick=async()=>{settingsRec.snoozeUntil=new Date(Date.now()+settingsRec.snoozeMinutes*60000).toISOString();await saveSettings();$('#alertBanner').classList.add('hidden');toast(`Pospuesto ${settingsRec.snoozeMinutes} min`)};$('#dismissAlertBtn').onclick=()=>$('#alertBanner').classList.add('hidden');
$('#importFileBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());const n=await importLegacy(d);toast(`Importadas ${n} tareas`);await render()}catch(err){toast(err.message)}};$('#importBundledBtn').onclick=async()=>{if(!confirm('¿Importar el estado de Taskium incluido en este paquete?'))return;try{const d=await fetch('./legacy/app_state.json').then(r=>r.json());const n=await importLegacy(d);toast(`Importadas ${n} tareas`);await render()}catch(e){toast(e.message)}};
window.addEventListener('online',()=>syncAll().then(render).catch(()=>renderStatus()));window.addEventListener('offline',renderStatus);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
await render();syncAll().then(render).catch(()=>{});
